### PR TITLE
Fix for Issues 37 and 39 

### PR DESCRIPTION
**Pull request by pshafton**
This is a fix for the inability to authenticate against aws china.

https://github.com/dasein-cloud/dasein-cloud-aws/issues/37

### CODE REVIEW

**Comment by pshafton** [comment]
@maksimov Any chance you can take a look at this pull request and issues 37 and 39. I'm trying to use this this for connecting and controlling instances in AWS China and the domain name structure is slightly different than the rest of the aws world.

**Comment by maksimov** [comment]
Looks good to me. @drewlyall, can you please merge and release?

**Comment by pshafton** [comment]
@drewlyall I don't see a release yet. Can you make a new release when you get a chance.

**Comment by drewlyall** [comment]
@pshafton It's out now.

**Comment by pshafton** [comment]
Awesome. Thanks.

**Pull request merged**
